name-template: v$NEXT_PATCH_VERSION 🌈

categories:
  - title: 🚀 Features
    labels:
      - kind/feature
      - kind/enhancement

  - title: 🐛 Bug Fixes
    labels:
      - kind/bug

  - title: 🔖 Documentation
    labels:
      - kind/docs

  - title: 💅 Style
    labels:
      - kind/style

  - title: 🧪 Test suite
    labels:
      - kind/test

  - title: 🧰 Maintenance
    labels:
      - kind/ci
      - kind/chore

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
