name-template: v$NEXT_PATCH_VERSION 🌈
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🔖 Documentation
    labels:
      - documentation
  - title: 🧰 Maintenance
    labels:
      - ci
      - chore
template: |
  ## Changes

  $CHANGES
